version: '3'
services:
    web:
        image: nginx:latest
        container_name: nginx_host
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/ssl:/etc/ssl"
            - "./web/:/var/www/html"
            - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        working_dir: /var/www/html/
        ports:
            - "80:80"
        depends_on:
            - php
            - db
    php:
        build: docker/php
        container_name: php
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
            - "./web/:/var/www/html"
        environment:
            DATABASE_HOST: db
        depends_on:
            - db

    db:
        image: mysql:8.0.21
        container_name: mysql_host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
        - ./docker/db/data:/var/lib/mysql
        - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
        - 3306:3306

    phpmyadmin:
        container_name: test_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        - PMA_HOSTS=mysql_host
        - PMA_USER=docker
        - PMA_PASSWORD=docker
        links:
        - db
        ports:
        - 8080:80
        volumes:
        - /sessions